### ISSUE TITLE
Text on links is clipped in svg

### ISSUE THREAD

**Issue by dlip** [mermaidjs/mermaid.cli#45]
All text on links in the flowchart is clipped

![screen shot 2018-08-01 at 1 37 18 pm](https://user-images.githubusercontent.com/283316/43499705-32966170-9590-11e8-949f-43cd9e1d2b01.png)

**Comment by Adverbly** [comment]
I'm also getting this.. tried changing the size as well as using flowchart useMaxWidth but haven't found a fix yet...

**Comment by roypa** [comment]
Me too. The width is hard coded on the `foreignObject` element, so difficult to apply CSS to fix this.

I managed to fix this by adding this to a CSS file:
```css
svg g.edgeLabel foreignObject {
  font-size: 1.2rem;
}
``` 

So I keep this temporarily until this is fixed by this issue.

**Comment by goek-han** [comment]
Same here for png and pdf

**Comment by IfElseSwitch** [comment]
Hi, I found another workaround with css, based on @roypa 's comment: 

```css
svg g.edgeLabel foreignObject {
  overflow: visible;
}
```

For my use case, changing the font-size did not fix the clipping, but did change the size of the label.

For information, changing the box width using the `!important` css rule works, but this shifts the boxes position.

**Comment by hxcaine** [comment]
This is happening to me too, although @IfElseSwitch's workaround fixes it for me.

Interestingly, the extent of the clipping differs according to the text inside the link text. Example from the Live Editor [here](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbiAgYS0tPmJbYl1cbiAgYi0tPnxmZmZmZjFmZmZmZjJmZmZmZjNmZmZmZjRmZmZmZjV8IGNbd2lkZSBsYWJlbCBoZXJlLi4uLi4uLi4uLl1cbiAgYi0tPnxhYWFhYTFhYWFhYTJhYWFhYTNhYWFhYTRhYWFhYTV8IGRcbiAgYi0tPnx3d3d3dzF3d3d3dzJ3d3d3dzN3d3d3dzR3d3d3dzV8IGYiLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ):

![image](https://user-images.githubusercontent.com/858227/55594501-dcac9500-570d-11e9-87db-c24b8c7c7a43.png)

**Comment by JTPearce** [comment]
Also getting this when using the default example on the [live editor](https://mermaidjs.github.io/mermaid-live-editor/). @IfElseSwitch's workaround doesn't stop the "Car" text from clipping unfortunately.

**Comment by redsand** [comment]
This fixed it for me on both use cases

`svg g.edgeLabel foreignObject {
  overflow: visible;
}

svg g.label foreignObject {
  overflow: visible;
}
`

**Comment by gustavnikolaj** [comment]
I experienced the same problem - but only when running it through the cli. The CLI uses puppeteer so I assumed that the bug was caused by the puppeteer chrome-instance using a different font when rendering it, than the browser I used to preview the result.

Each of the foreignObject nodes have an explicit width set in an attribute. That width is probably based on measurements taking place in the headless-browser. If the font selected in that browser is different from the font selected in the rendering browser, then you could see the difference in width that is reported here - and also varying between individual cases as reported by users in this issue.

I wasn't seeing any problem on the actual nodes (the purple bordered boxes) but only on labels on edges.

I noticed that the edges has this style applied to them, when inspecting them in my actual browser:

```
#mermaid-1559556687081 .label {
    font-family: trebuchet ms,verdana,arial;
    color: #333;
}
```

Trebuchet MS is installed on my machine, and it is the font that my browser actually uses when rendering the nodes.

If I disable that rule in my browser, then the text shows as expected. 

The font that it falls back to is Times New Roman, which is also installed on my system, coming from a less specific CSS rule:

```
#mermaid-1559557060931 {
    color: rgb(0, 0, 0);
    font: normal normal 400 normal 16px / normal "Times New Roman";
}
```

If I disable that rule as well, I get the user-agent stylesheets fallback font, which in my case is Times, which seems to have identical proportions to Times New Roman.

To me that indicates that either...

- puppeteer doesn't have access to the same font files that I have on my system browser, meaning that it falls back on other fonts
- or the css is simply not applied when the measurements are made.

Adding a stylesheet with the font-family rule, when invoking the `mmdc` script, solves the problem for me, which seems to suggest that it is the latter.

```css
svg g.edgeLabel foreignObject span.edgeLabel {
    font-family: trebuchet ms,verdana,arial;
}
```

**Comment by redsand** [comment]
I reascend my previous comment.  It looks like it's related to some css not being applied during distance/spacial calculations.  The font text is visible when disabling "font-size: 11.844px;" in the bootstrap.css .label .badge entry.  But when commenting it out and reloading the page, the issue is the same, except the font is simply smaller.  It's only properly sized when manually disabling the font-size limitation in the browser after rendering.   This certainly has something to do with it being embedded with angularjs, however ngMermaid simply doesn't work for me.

**Comment by davinkevin** [comment]
Having the same problem, I will try to use the solution from @gustavnikolaj but would be good to have a workaround. 

I'm using mmdc for `asciidoc` documentation, so it's a lot of plumbing to fix this puppeteer problem.

**Comment by X-Ryl669** [comment]
The issue boils down to mermaid-js's use of `getBoundingClientRect()` of a DOMNode. This does not account for margin or padding. In flowchart, there isn't any option to add a margin/padding anyway so this can't be resolved in mermail.cli, IFAIK, but in mermaid-js when/if they add margin for those.

**Comment by sagho0or** [comment]
I had the same problem .and this fixed by using 8.3.1 version instead of 8.4.6 .

**Comment by niclas-g** [comment]
Still a problem for me in  mermaid-cli 8.9.2 /  mermaid: 8.9.3
